server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: api-protegida-entra
  
  # Configuración de Microsoft Entra ID (Azure AD)
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: f128ae87-3797-42d7-8490-82c6b570f832
        credential:
          client-id: 4a12fbd8-bf63-4c12-be4c-9678b207fbe7
          client-secret: wTu8Q~nC5v31H6fYqV8HKX9M3zIz1b.UQSt0hcr5
        app-id-uri: api://4a12fbd8-bf63-4c12-be4c-9678b207fbe7
        authorization-clients:
          angular-client:
            scopes:
              - access_as_user

  # Configuración de base de datos H2 (para desarrollo)
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  
  sql:
    init:
      mode: always

  # Configuración de seguridad OAuth2
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/f128ae87-3797-42d7-8490-82c6b570f832/v2.0
          audiences: 
            - api://4a12fbd8-bf63-4c12-be4c-9678b207fbe7
            - 4a12fbd8-bf63-4c12-be4c-9678b207fbe7

# Configuración de logging
logging:
  level:
    com.example.apiprotegida: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Configuración de CORS para Angular
cors:
  allowed-origins: "http://localhost:4200,https://localhost:4200"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true

# Configuración de Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
